# Generated by Django 3.0.5 on 2021-09-02 10:50

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('middle_name', models.CharField(default='', max_length=30, verbose_name='Middle name')),
                ('position', models.CharField(max_length=30, verbose_name='Position')),
                ('private_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Private')),
                ('work_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Work_phone')),
                ('fax', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Fax')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='Title')),
                ('address', models.TextField(max_length=30, verbose_name='Address')),
                ('description', models.TextField(max_length=30, verbose_name='Description')),
                ('employee', models.ManyToManyField(max_length=30, to='api.Employee')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Employee')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Organisation')),
            ],
        ),
    ]
