# Generated by Django 3.0.5 on 2021-09-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usereditor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='owner',
        ),
    ]
