# Generated by Django 3.0.5 on 2021-09-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_organisation_owner'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employee',
            name='unique_organisations_employee',
        ),
        migrations.AddConstraint(
            model_name='usereditor',
            constraint=models.UniqueConstraint(fields=('user', 'organisation'), name='unique_user_organisation'),
        ),
    ]
